FORMAT: 1A
HOST: https://hoshisora000.lionfree.net/api

# ai&app_project

期末專題用，API說明文件
如需閱讀，請參閱: https://aiappproject.docs.apiary.io/

# 允許的HTTPs請求方式:
 - POST    : 更新資源
 - GET     : 獲取單一資源或資源列表
 - DELETE  : 刪除資源


# 伺服器回應的描述:
- 200 `OK` - 請求成功（某些API呼叫可能返回201）。
- 201 `Created` - 請求成功並且創建了一個資源。
- 400 `Bad Request` - 無法理解請求或缺少必要的參數。
- 403 `Forbidden` - 拒絕訪問。
- 404 `Not Found` - 找不到資源。
- 500 `Internal Server Error` - 內部伺服器錯誤
- 501 `Not Implemented` - 伺服器目前不支援此功能(錯誤訊息存於error_log)


## 新增發票 [/add_invoice.php]

### 上傳發票資料[POST]

接收發票資料並存入資料庫。<br>
<b>form-data須注意相關格式(值前面務必空一行)</b>

+ Request (multipart/form-data; boundary={boundary value})

    + Attributes
        + uid (string, required) - 使用者ID
        + invoice_number (string, required) - 發票號碼
        + date (string, required) - 發票日期
        + time (string, required) - 發票時間
        + money (string, required) - 發票金額    

    + Body

        --{boundary value}
        Content-Disposition: form-data; name="uid"
        
        O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6
        --{boundary value}
        Content-Disposition: form-data; name="invoice_number"
        
        ZZ12345678
        --{boundary value}
        Content-Disposition: form-data; name="date"
        
        2023-05-21
        --{boundary value}
        Content-Disposition: form-data; name="time"
        
        21:26:55
        --{boundary value}
        Content-Disposition: form-data; name="money"
        
        32
        --{boundary value}--

+ Response 200 (application/json)

    + Body

        {
            "data": {
                "uid": "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6",
                "invoice_number": "ZZ12345678"
            },
            "status": {
                "code": "201",
                "message": "Success",
                "datetime": "2023-05-2200:50:38(+08:00)"
            }
        }

+ Response 400 (application/json)

    + Body

        {
            "data": [],
            "status": {
                "code": "400",
                "message": "資料有缺漏/資料格式錯誤",
                "datetime": "2023-05-2213:36:15(+08:00)"
            }
        }

+ Response 404 (application/json)

    + Body

        {
            "data": [],
            "status": {
                "code": "404",
                "message": "重複的發票號碼",
                "datetime": "2023-05-2210:54:37(+08:00)"
            }
        }

+ Response 500 (application/json)

    + Body

        {
            "data": [],
            "status": {
                "code": "500",
                "message": "內部伺服器錯誤",
                "datetime": "2023-05-2214:23:33(+08:00)"
            }
        }


## 查詢發票 [/query_invoice.php]

### 查詢會員發票 [GET]

提供查詢使用者所有的發票。

- Parameters

  - uid: "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6" (string, required) - 使用者ID


+ Response 200 (application/json)

        {
            "data": [
                {
                    "uid": "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6",
                    "invoice_number": "AA54578621",
                    "date": "2023-05-21",
                    "time": "14:24:00",
                    "money": "777"
                },
                {
                    "uid": "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6",
                    "invoice_number": "NQ1234569",
                    "date": "2023-05-12",
                    "time": "21:31:00",
                    "money": "100"
                }
            ],
            "status": {
                "amount": 2,
                "code": "0",
                "message": "Success",
                "datetime": "2023-05-2211:23:24(+08:00)"
            }
        }

+ Response 400 (application/json)

    [
            
    ]
    
    

## 刪除發票 [/delete_invoice.php]

### 上傳發票資料[POST]

刪除資料庫中指定的發票。




- Parameters
    - uid: "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6" (string, required) - 使用者ID
    - invoice: "ZZ12345678" (string, required) - 發票號碼

+ Response 200 (application/json)

    + Body

        {
            "data": {
                "uid": "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6",
                "invoice_number": "ZZ12345678"
            },
            "status": {
                "code": "201",
                "message": "Success",
                "datetime": "2023-05-2200:50:38(+08:00)"
            }
        }

+ Response 400 (application/json)

    + Body

        {
            "data": [],
            "status": {
                "code": "400",
                "message": "資料有缺漏/資料格式錯誤",
                "datetime": "2023-05-2213:36:15(+08:00)"
            }
        }

+ Response 404 (application/json)

    + Body

        {
            "data": [],
            "status": {
                "code": "404",
                "message": "重複的發票號碼",
                "datetime": "2023-05-2210:54:37(+08:00)"
            }
        }

+ Response 500 (application/json)

    + Body

        {
            "data": [],
            "status": {
                "code": "500",
                "message": "內部伺服器錯誤",
                "datetime": "2023-05-2214:23:33(+08:00)"
            }
        }