FORMAT: 1A
HOST: https://hoshisora000.lionfree.net/api

# ai&app_project

期末專題用，API說明文件
如需閱讀，請參閱: https://aiappproject.docs.apiary.io/

# 允許的HTTPs請求方式:
 - POST    : 更新資源
 - GET     : 獲取單一資源或資源列表
 - DELETE  : 刪除資源


# 伺服器回應的描述:
- 200 `OK` - 請求成功。
- 201 `Created` - 請求成功並且創建了一個資源。
- 400 `Bad Request` - 無法理解請求或缺少必要的參數。
- 403 `Forbidden` - 拒絕訪問。
- 404 `Not Found` - 找不到資源。
- 405 `Method Not Allowed` - 伺服器理解此請求方法，但它被禁用或不可用。
- 500 `Internal Server Error` - 內部伺服器錯誤(錯誤訊息存於error_log)。
- 501 `Not Implemented` - 伺服器目前不支援此功能。


## 新增發票 [/add_invoice.php]

### 新增發票[POST]

接收發票資料存入資料庫。

+ Request

    + Attributes
        + uid (string, required) - 使用者ID
        + invoice_number (string, required) - 發票號碼
        + date (string, required) - 發票日期
        + time (string, required) - 發票時間
        + money (string, required) - 發票金額    

    + Body
    
        {
            uid:O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6
            invoice_number:ZZ12345678
            date:2023-05-22
            time:10:22:33
            money:542
        }

+ Response 200

    + Body (application/json)
        
        {
            "data": {
                "uid": "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6",
                "invoice_number": "ZZ12345678"
            },
            "status": {
                "code": "201",
                "message": "發票新增成功",
                "datetime": "2023-05-22 00:50:38 (+08:00)"
            }
        }
        

+ Response 400

    + Body(application/json)
    
        {
            "data": [],
            "status": {
                "code": "400",
                "message": "資料有缺漏/資料格式錯誤",
                "datetime": "2023-05-2213:36:15(+08:00)"
            }
        }

        

+ Response 500

    + Body(application/json)
        
        {
            "data": [],
            "status": {
                "code": "500",
                "message": "內部伺服器錯誤",
                "datetime": "2023-05-2214:23:33(+08:00)"
            }
        }


## 新增會員 [/add_member_inf.php]

### 新增會員資料[POST]

接收會員資料存入資料庫。

+ Request (multipart/form-data)

    + Attributes
        + uid (string, required) - 使用者ID
        + nickname (string, required) - 暱稱
        + mobile_barcode (string, required) - 手機載具

    + Body
        uid:hAonkFh8d3WLtpebxHtJKlQD5w92
        nickname:7666
        mobile_barcode:

+ Response 200 (application/json)

    + Body(application/json)
        {
            "data": {
                "uid": "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6",
                "invoice_number": "ZZ12345678"
            },
            "status": {
                "code": "201",
                "message": "發票新增成功",
                "datetime": "2023-05-2200:50:38(+08:00)"
            }
        }

+ Response 400 (application/json)

    + Body(application/json)
        {
            "data": [],
            "status": {
                "code": "400",
                "message": "資料有缺漏/資料格式錯誤",
                "datetime": "2023-05-2213:36:15(+08:00)"
            }
        }

+ Response 500 (application/json)

    + Body(application/json)
        {
            "data": [],
            "status": {
                "code": "500",
                "message": "內部伺服器錯誤",
                "datetime": "2023-05-2214:23:33(+08:00)"
            }
        }


## 會員分析 [/analysis.php]

### 會員分析[POST]

分析會員消費習慣。

+ Request (multipart/form-data)

    + Attributes
        + uid (string, required) - 使用者ID
        + year_month (string, required) - 時間(年月)

    + Body
        uid:hAonkFh8d3WLtpebxHtJKlQD5w92
        year_month:11205

+ Response 200 (application/json)

    + Body (application/json)
        {
            "record": 3,
            "data": {
                "midnight": 1,
                "midnight_money": 66,
                "morning": 2,
                "morning_money": 1027,
                "afternoon": 0,
                "afternoon_money": 0,
                "night": 0,
                "night_money": 0
            },
            "status": {
                "code": "200",
                "message": "查詢成功",
                "datetime": "2023-06-1100:43:00(+08:00)"
            }
        }

+ Response 400

    + Body (application/json)
        {
            "data": [],
            "status": {
                "code": "400",
                "message": "資料有缺漏/資料格式錯誤",
                "datetime": "2023-05-2213:36:15(+08:00)"
            }
        }

+ Response 500

    + Body (application/json)
        {
            "data": [],
            "status": {
                "code": "500",
                "message": "內部伺服器錯誤",
                "datetime": "2023-05-2214:23:33(+08:00)"
            }
        }
        
## 會員中獎查詢 [/check_invoice.php]

### 會員發票中獎查詢[POST]

分析會員消費習慣。

+ Request (multipart/form-data)

    + Attributes
        + uid (string, required) - 使用者ID
        + period (string, required) - 發票期數

    + Body
        uid:hAonkFh8d3WLtpebxHtJKlQD5w92
        year_month:11205

+ Response 200 

    + Body(application/json)
        {
            "record": 3,
            "data": {
                "midnight": 1,
                "midnight_money": 66,
                "morning": 2,
                "morning_money": 1027,
                "afternoon": 0,
                "afternoon_money": 0,
                "night": 0,
                "night_money": 0
            },
            "status": {
                "code": "200",
                "message": "查詢成功",
                "datetime": "2023-06-1100:43:00(+08:00)"
            }
        }

+ Response 400 

    + Body(application/json)
        {
            "record": 0,
            "data": [],
            "status": {
                "code": "400",
                "message": "資料有缺漏/資料格式錯誤",
                "datetime": "2023-05-2213:36:15(+08:00)"
            }
        }

+ Response 500 

    + Body(application/json)
        {
            "record": 0,
            "data": [],
            "status": {
                "code": "500",
                "message": "內部伺服器錯誤",
                "datetime": "2023-05-2214:23:33(+08:00)"
            }
        }

## 發票對獎 [/check_winning.php]

### 發票對獎[GET]

分析會員消費習慣。

- Parameters

  - period: "1120102" (string, required) - 發票期數
  - invoice_number: "AB12345678" (string, required) - 發票號碼

+ Response 200 

    + Body(application/json)
        {
            "data": {
                "win": 1,
                "winning_amount": 4000,
                "return_for_user": null
            },
            "status": {
                "code": "200",
                "message": "查詢成功",
                "datetime": "2023-06-1101:10:15(+08:00)"
            }
        }

+ Response 400 

    + Body(application/json)
        {
            "data": [],
            "status": {
                "code": "400",
                "message": "發票號碼格式錯誤",
                "datetime": "2023-06-1101:10:27(+08:00)"
            }
        }

+ Response 500 更新ap

    + Body(application/json)
        {
            "record": 0,
            "data": [],
            "status": {
                "code": "500",
                "message": "內部伺服器錯誤",
                "datetime": "2023-05-2214:23:33(+08:00)"
            }
        }

## 查詢發票 [/query_invoice.php]

### 查詢發票 [GET]

提供查詢使用者所有的發票。

- Parameters

  - uid: "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6" (string, required) - 使用者ID


+ Response 200
    + Body
        {
            "data": [
                {
                    "uid": "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6",
                    "invoice_number": "AA54578621",
                    "date": "2023-05-21",
                    "time": "14:24:00",
                    "money": "777"
                },
                {
                    "uid": "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6",
                    "invoice_number": "NQ1234569",
                    "date": "2023-05-12",
                    "time": "21:31:00",
                    "money": "100"
                }
            ],
            "status": {
                "amount": 2,
                "code": "0",
                "message": "Success",
                "datetime": "2023-05-2211:23:24(+08:00)"
            }
        }

+ Response 400 

    [
            
    ]
    
    

## 刪除發票 [/delete_invoice.php]

### 刪除發票[POST]

刪除資料庫中指定的發票。




- Attributes
    - uid (string, required) - 使用者ID
    - invoice_number (string, required) - 發票號碼

+ Response 200 (application/json)

    + Body

        {
            "data": {
                "uid": "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6",
                "invoice_number": "ZZ12345678"
            },
            "status": {
                "code": "201",
                "message": "Success",
                "datetime": "2023-05-2200:50:38(+08:00)"
            }
        }

+ Response 400 (application/json)

    + Body

        {
            "data": [],
            "status": {
                "code": "400",
                "message": "資料有缺漏/資料格式錯誤",
                "datetime": "2023-05-2213:36:15(+08:00)"
            }
        }

+ Response 404 (application/json)

    + Body

        {
            "data": [],
            "status": {
                "code": "404",
                "message": "重複的發票號碼",
                "datetime": "2023-05-2210:54:37(+08:00)"
            }
        }

+ Response 500 (application/json)

    + Body

        {
            "data": [],
            "status": {
                "code": "500",
                "message": "內部伺服器錯誤",
                "datetime": "2023-05-2214:23:33(+08:00)"
            }
        }
        
## 查詢會員資料 [/query_member.php]

### 查詢會員資料 [GET]

查詢會員資料。

- Parameters

  - uid: "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6" (string, required) - 使用者ID


+ Response 200 (application/json)

        {
            "data": [
                {
                    "uid": "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh6",
                    "nickname": "??",
                    "mobile_barcode": "87878740"
                }
            ],
            "status": {
                "amount": 1,
                "code": "0",
                "message": "Success",
                "datetime": "2023-05-2913:35:52(+08:00)"
            }
        }

+ Response 400 (application/json)

    [
            
    ]       
    

        

## 修改會員資料 [/update_member_inf.php]

### 修改會員資料 [POST]

修改會員資料。

+ Attributes
    
    + uid (string, required) - 使用者ID
    + nickname (string, required) - 暱稱
    + mobile_barcode (string, required) - 手機條碼   


+ Response 200 (application/json)

        {
            "data": {
                "uid": "O2g8sZF0nMh1ZJaq8M6xh6w5CnD2O2g8sZF0nMh1ZJaq8M6xh677",
                "nickname": "OwO",
                "mobile_barcode": "7777777"
            },
            "status": {
                "amount": null,
                "code": "0",
                "message": "Success",
                "datetime": "2023-05-2914:34:12(+08:00)"
            }
        }